In [ ]:
import torch
import numpy
import pandas as pd

In [ ]:
x_min=0
x_max=2
t_min=0
t_max=2
total_points_x=4
total_points_t=4

In [ ]:
x = torch.linspace(x_min, x_max, 4).view(-1,1)
t = torch.linspace(t_min, t_max, 4).view(-1,1)

In [ ]:
X, T = torch.meshgrid(x.squeeze(1),t.squeeze(1))
print(X)
print("---------------------------------------")
print(T)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.6667, 0.6667, 0.6667, 0.6667],
        [1.3333, 1.3333, 1.3333, 1.3333],
        [2.0000, 2.0000, 2.0000, 2.0000]])
---------------------------------------
tensor([[0.0000, 0.6667, 1.3333, 2.0000],
        [0.0000, 0.6667, 1.3333, 2.0000],
        [0.0000, 0.6667, 1.3333, 2.0000],
        [0.0000, 0.6667, 1.3333, 2.0000]])


/usr/local/lib/python3.7/dist-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [ ]:
X.flatten()

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.6667, 0.6667, 0.6667, 0.6667, 1.3333,
        1.3333, 1.3333, 1.3333, 2.0000, 2.0000, 2.0000, 2.0000])

In [ ]:
X.T.flatten()

tensor([0.0000, 0.6667, 1.3333, 2.0000, 0.0000, 0.6667, 1.3333, 2.0000, 0.0000,
        0.6667, 1.3333, 2.0000, 0.0000, 0.6667, 1.3333, 2.0000])

In [ ]:
X.transpose(1,0).flatten()

tensor([0.0000, 0.6667, 1.3333, 2.0000, 0.0000, 0.6667, 1.3333, 2.0000, 0.0000,
        0.6667, 1.3333, 2.0000, 0.0000, 0.6667, 1.3333, 2.0000])

In [ ]:
T.flatten()

tensor([0.0000, 0.6667, 1.3333, 2.0000, 0.0000, 0.6667, 1.3333, 2.0000, 0.0000,
        0.6667, 1.3333, 2.0000, 0.0000, 0.6667, 1.3333, 2.0000])

In [ ]:
T.T.flatten()

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.6667, 0.6667, 0.6667, 0.6667, 1.3333,
        1.3333, 1.3333, 1.3333, 2.0000, 2.0000, 2.0000, 2.0000])

In [ ]:
x_test = torch.hstack((X.flatten()[:,None],T.flatten()[:,None])) #row major
pd.DataFrame(x_test, columns=["X","T"])

X               T
0       tensor(0.)      tensor(0.)
1       tensor(0.)  tensor(0.6667)
2       tensor(0.)  tensor(1.3333)
3       tensor(0.)      tensor(2.)
4   tensor(0.6667)      tensor(0.)
5   tensor(0.6667)  tensor(0.6667)
6   tensor(0.6667)  tensor(1.3333)
7   tensor(0.6667)      tensor(2.)
8   tensor(1.3333)      tensor(0.)
9   tensor(1.3333)  tensor(0.6667)
10  tensor(1.3333)  tensor(1.3333)
11  tensor(1.3333)      tensor(2.)
12      tensor(2.)      tensor(0.)
13      tensor(2.)  tensor(0.6667)
14      tensor(2.)  tensor(1.3333)
15      tensor(2.)      tensor(2.)

In [ ]:
x_test_T = torch.hstack((X.T.flatten()[:,None],T.T.flatten()[:,None])) #Column major which simulates Time Marching
pd.DataFrame(x_test_T, columns=["X","T"])

X               T
0       tensor(0.)      tensor(0.)
1   tensor(0.6667)      tensor(0.)
2   tensor(1.3333)      tensor(0.)
3       tensor(2.)      tensor(0.)
4       tensor(0.)  tensor(0.6667)
5   tensor(0.6667)  tensor(0.6667)
6   tensor(1.3333)  tensor(0.6667)
7       tensor(2.)  tensor(0.6667)
8       tensor(0.)  tensor(1.3333)
9   tensor(0.6667)  tensor(1.3333)
10  tensor(1.3333)  tensor(1.3333)
11      tensor(2.)  tensor(1.3333)
12      tensor(0.)      tensor(2.)
13  tensor(0.6667)      tensor(2.)
14  tensor(1.3333)      tensor(2.)
15      tensor(2.)      tensor(2.)

In [ ]:
x_test_Tt = torch.hstack((X.transpose(1,0).flatten()[:,None],T.transpose(1,0).flatten()[:,None])) #Column major which simulates Time Marching
pd.DataFrame(x_test_Tt, columns=["X","T"])

X               T
0       tensor(0.)      tensor(0.)
1   tensor(0.6667)      tensor(0.)
2   tensor(1.3333)      tensor(0.)
3       tensor(2.)      tensor(0.)
4       tensor(0.)  tensor(0.6667)
5   tensor(0.6667)  tensor(0.6667)
6   tensor(1.3333)  tensor(0.6667)
7       tensor(2.)  tensor(0.6667)
8       tensor(0.)  tensor(1.3333)
9   tensor(0.6667)  tensor(1.3333)
10  tensor(1.3333)  tensor(1.3333)
11      tensor(2.)  tensor(1.3333)
12      tensor(0.)      tensor(2.)
13  tensor(0.6667)      tensor(2.)
14  tensor(1.3333)      tensor(2.)
15      tensor(2.)      tensor(2.)

In [ ]:
x_test_T == x_test_Tt

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])